### ISSUE TITLE
The unit tests workflow runs twice on PRs

### ISSUE THREAD

**Issue by mbaluda** [advanced-security/codeql-development-toolkit#6]
The [template](https://github.com/advanced-security/codeql-development-toolkit/blob/master/src/CodeQLToolkit.Features.Test/Templates/Test/Actions/run-unit-tests.liquid#L7) should be changed to
```
push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
```
